```mermaid  
  classDiagram  
    class Calculator {  
      +void calculate(op: str, a: float, b: float)  
      +void run_interactive()  
      +void run_gui()  
      +static get_today_date()  
    }  
    class OPS {  
      +add()  
      +sub()  
      +mul()  
      +div()  
      +pow()  
      +mod()  
      +sqrt()  
      +pct()  
    }  
    Calculator --> OPS
```