```mermaid
  databaseEntity
    User {
      ID int;
      Name string;
      Email string;
    }
    Operation {
      ID int;
      Type string;
      Operand1 float;
      Operand2 float;
    }
```