#!/usr/bin/env python3
"""
Sync all docs/diagrams/*.mmd files into a single docs/diagrams-preview.md
so they can be viewed together in Markdown preview (Ctrl+Shift+V).

Can be run standalone or called from generate_docs.py after diagram generation.

Usage:
  python scripts/sync_diagrams_preview.py
  python scripts/sync_diagrams_preview.py --repo /path/to/repo
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPT_DIR.parent
for _p in (str(_REPO_ROOT), str(_SCRIPT_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import config as pipeline_config

_FENCE_RE = re.compile(r"^\s*```\s*mermaid\s*$", re.MULTILINE)
_FENCE_CLOSE_RE = re.compile(r"^\s*```\s*$", re.MULTILINE)

_MERMAID_KEYWORDS = re.compile(
    r"^\s*(?:graph|flowchart|sequenceDiagram|classDiagram|stateDiagram|erDiagram|"
    r"gantt|pie|gitGraph|journey|mindmap|timeline|quadrantChart|sankey|xychart|block)",
    re.MULTILINE,
)

_FRIENDLY_NAMES: dict[str, str] = {
    "architecture.mmd": "Architecture",
    "state-machine.mmd": "State Machine",
    "class.mmd": "Class Diagram",
    "database-entity.mmd": "Database Entity",
}


def _extract_mermaid_body(raw: str) -> str:
    """Strip surrounding ```mermaid ... ``` fences if present, return inner code."""
    opening = _FENCE_RE.search(raw)
    if not opening:
        return raw.strip()
    after_open = raw[opening.end():]
    closing = _FENCE_CLOSE_RE.search(after_open)
    if not closing:
        return after_open.strip()
    return after_open[: closing.start()].strip()


def sync_preview(repo_path: str = ".") -> Path:
    """Read every .mmd diagram and write a unified diagrams-preview.md."""
    repo = Path(repo_path)
    diagrams_dir = repo / pipeline_config.APPROVED_DIAGRAMS_DIR
    output_path = repo / pipeline_config.APPROVED_DOCS_DIR / "diagrams-preview.md"

    lines = [
        "# Diagrams Preview",
        "",
        "Open this file in Markdown preview (`Ctrl+Shift+V`) to view all diagrams.",
        "",
        "<!-- AUTO-GENERATED by scripts/sync_diagrams_preview.py — do not edit manually -->",
        "",
    ]

    for filename in pipeline_config.REQUIRED_DIAGRAMS:
        mmd_path = diagrams_dir / filename
        friendly = _FRIENDLY_NAMES.get(filename, filename)

        lines.append(f"## {friendly}")
        lines.append("")

        if not mmd_path.exists():
            lines.append(f"*`{filename}` not found.*")
            lines.append("")
            continue

        raw = mmd_path.read_text(encoding="utf-8", errors="replace")
        body = _extract_mermaid_body(raw)

        if not body or body.isspace():
            lines.append(f"*`{filename}` is empty.*")
            lines.append("")
            continue

        if _MERMAID_KEYWORDS.search(body):
            lines.append("```mermaid")
            lines.append(body)
            lines.append("```")
        else:
            lines.append(f"> {body}")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync .mmd diagrams into diagrams-preview.md")
    parser.add_argument("--repo", default=".", help="Repository root (default: cwd)")
    args = parser.parse_args()

    out = sync_preview(args.repo)
    print(f"Wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
